### ISSUE TITLE
Exclude filter for (Virtual Console)

### ISSUE THREAD

**Issue by MaXGitteR** [unexpectedpanda/retool#11]
Please add an exclude filter for "Virtual Console"
maybe also "Switch Online"

**Comment by unexpectedpanda** [comment]
Is your request because many of these don't work in emulators?

Currently, these are selected above all other versions. The next revision however demotes these titles, which should be effectively the same thing as filtering them out.

Unless you've got another use case, I'll carry on making that change.

**Comment by MaXGitteR** [comment]
I have not yet figured out if the are good or bad for emulators, I only saw them and I don't have them.
i think people may want both - some high and some low prio, so should we give them the choice and treat it like a region?

**Comment by unexpectedpanda** [comment]
I'll put some thought into it. There are design and intent ramifications beyond just this one feature.

**Comment by unexpectedpanda** [comment]
Retool 0.86 demoted titles that had been ripped from modern platforms by default.

Retool 0.87, which will be out shortly, continues this and expands on the number of titles considered. If you prefer the modern ripped titles to be the 1G1R title instead, you can select that option in the **Modes** tab.
