### ISSUE TITLE
Sega Mega Drive - Sonic & Knuckles classed as child of Sonic & Knuckles + Sonic The Hedgehog 3

### ISSUE THREAD

**Issue by a60wattfish** [unexpectedpanda/retool#111]
## Dat
Sega - Mega Drive - Genesis (20210427-223151).dat

## Issue
The standalone Sonic & Knuckles game has been classed as a child of Sonic & Knuckles + Sonic The Hedgehog 3 (USA) when it should be a seperate parent.

Sonic & Knuckles has a pass through feature which lets you "combine" that game with another Sonic one, changing the game in some way. The entries for "Sonic & Knuckles + Sonic The Hedgehog" and "Sonic & Knuckles + Sonic The Hedgehog 2" are already classed as seperate entries. The "Sonic & Knuckles" game is quite different from when it is combined with "Sonic The Hedgehog 3" There is some brief information on it at https://en.wikipedia.org/wiki/Sonic_%26_Knuckles#Lock-on_technology.

The current listing is:
```
Sonic & Knuckles + Sonic The Hedgehog 3 (USA)	
├	Sonic & Knuckles (World)
├	Sonic & Knuckles (World) (Beta) (1994-05-25)
├	Sonic & Knuckles (World) (Beta) (1994-06-06)
├	Sonic & Knuckles (World) (Beta) (1994-06-08)
├	Sonic & Knuckles (World) (Beta) (1994-06-10)
├	Sonic & Knuckles (World) (Beta) (1994-06-12)
├	Sonic & Knuckles (World) (Beta) (1994-06-18)
├	Sonic & Knuckles (World) (Beta) (1994-06-19)
├	Sonic & Knuckles (World) (Sonic Classic Collection)
├	Sonic & Knuckles + Sonic The Hedgehog 2 + Sonic The Hedgehog 3 (World) (Virtual Console)
├	Sonic & Knuckles + Sonic The Hedgehog 3 (Europe)
├	Sonic & Knuckles + Sonic The Hedgehog 3 (Japan) (En)
├	Sonic The Hedgehog 3 Limited Edition (Japan) (En) (Proto) (1994-04-08)
└	Sonic The Hedgehog 3 Limited Edition (Japan) (En) (Proto) (1994-05-17)
```

The following should be broken off:
```
├	Sonic & Knuckles (World)
├	Sonic & Knuckles (World) (Beta) (1994-05-25)
├	Sonic & Knuckles (World) (Beta) (1994-06-06)
├	Sonic & Knuckles (World) (Beta) (1994-06-08)
├	Sonic & Knuckles (World) (Beta) (1994-06-10)
├	Sonic & Knuckles (World) (Beta) (1994-06-12)
├	Sonic & Knuckles (World) (Beta) (1994-06-18)
├	Sonic & Knuckles (World) (Beta) (1994-06-19)
├	Sonic & Knuckles (World) (Sonic Classic Collection)
```

"Sonic & Knuckles + Sonic The Hedgehog 2 + Sonic The Hedgehog 3 (World) (Virtual Console)" is another issue as it is a compilation containing all three games.

**Comment by unexpectedpanda** [comment]
Ah yeah, the Lock-on technology made this a tough decision. Ultimately I came to consider _Sonic & Knuckles + Sonic The Hedgehog 3_ a parent of _Sonic The Hedgehog 3_. Per Wikipedia:

> When Sonic 3 is inserted, the player can play through both games as one, Sonic 3 & Knuckles. This features several changes to the games, such as slightly altered level layouts, the ability to play through Sonic 3 levels as Knuckles or Sonic & Knuckles levels as Tails, and the ability to save progress in Sonic & Knuckles levels."

So on the surface it looks like adding more to each game, while encompassing both -- effectively making it a superset or special edition of the previous games. From a perspective of loss, it doesn't look like you're losing much by offering the bundled, "complete" version instead of the original titles. There might be something I'm unaware of -- I only got up to _Sonic 2_ back in the day before my gaming focus moved to PC.

Speaking of which, by the current logic, I've messed up the _Sonic 2_ entry. _Sonic & Knuckles + Sonic The Hedgehog 2_ really should be the parent of _Sonic The Hedgehog 2_, as it's the same game with Knuckles as a playable character. The _Sonic the Hedgehog_ Lock-on variant of _Blue Sphere_ however is a completely different game, so in my mind it makes sense to separate them.

> "Sonic & Knuckles + Sonic The Hedgehog 2 + Sonic The Hedgehog 3 (World) (Virtual Console)" is another issue as it is a compilation containing all three games.

Yep, that one causes fun. If you choose to make modern platform rereleases replace standard editions, it should become the parent of all the relevant Sonic titles. That's not actually the case due to the earlier mentioned _Sonic 2_ oversight, and gosh compilations always make things difficult from a programming point of view.

The preservationist in me fought against these decisions a little, as I get how each game is uniquely presented -- but ultimately the focus of Retool is meant to be to choose the _one_ game for a title, regardless of small differences, and this seems the more true choice. Hopefully I'm not off the mark here. By all means, open to being persuaded :)

I'll keep this open for now, as it highlights a few issues I'll need to address with the Mega Drive/Genesis clone list.

**Comment by unexpectedpanda** [comment]
Oh boy. Yep, so this is a bit more of a nightmare than I had thought, given region changes and the modern edition flag takes us down all sorts of unexpected twists and turns.

I've decoupled the _Sonic & Knuckles_ Lock-on versions from the standalone titles until such time as Retool can handle this scenario -- but it's just messy enough that it might have to be that way forever.

**Comment by a60wattfish** [comment]
> So on the surface it looks like adding more to each game, while encompassing both -- effectively making it a superset or special edition of the previous games. From a perspective of loss, it doesn't look like you're losing much by offering the bundled, "complete" version instead of the original titles. There might be something I'm unaware of -- I only got up to Sonic 2 back in the day before my gaming focus moved to PC.

After reading your explanation I can understand why Sonic and Knuckles was bundled with 3 and think you had probably made the right call with that one. There are only minimal changes to 3 in most cases when playing as Sonic or Tails, until you get to the end of 3 where the main boss is removed, but you are then put into Sonic and Knuckles. From a purist point of view this may not be great, but in that case they would probably be hand picking the games anyway.

> Speaking of which, by the current logic, I've messed up the Sonic 2 entry. Sonic & Knuckles + Sonic The Hedgehog 2 really should be the parent of Sonic The Hedgehog 2, as it's the same game with Knuckles as a playable character.

Yeah, I always thought there were more changes but I've looked into it now and it does minimal patching to the actual game so really is a special edition. When I play Sonic 2 now, I probably will just go straight for that version.

> The Sonic the Hedgehog Lock-on variant of Blue Sphere however is a completely different game, so in my mind it makes sense to separate them.

Yeah, agreed on this one.

> I've decoupled the Sonic & Knuckles Lock-on versions from the standalone titles until such time as Retool can handle this scenario -- but it's just messy enough that it might have to be that way forever.

Thanks for that, if you decide to revert that decision then I understand why.

**Comment by unexpectedpanda** [comment]
Looks like No-Intro recently removed the merged Lock-on ROMs from the DAT. Not sure why, perhaps emulation technology is good enough to handle that functionality now?

Regardless, I'll keep this open as this is an issue that I'll need to solve for other titles.

**Comment by unexpectedpanda** [comment]
The combined lock-on cartridges have returned, however Retool v2 can now handle them. For now I've split the locked-on cartridges from the original games.
