### ISSUE TITLE
Feature request: support for TOSEC-datfiles

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#115]
Hi,

I was wondering if it would be possible to add support for TOSEC datfiles? 

They released a new updated set just yesterday (https://www.tosecdev.org/downloads/category/53-2021-08-08) and I noticed Retool doesn't quite understand their tags in their naming convention (https://www.tosecdev.org/tosec-naming-convention)

Mainly I'm just needing a automated way to remove all the alternative, trained and other "unnecessary" roms.

I've been testing this with mainly datfiles;
"Amstrad CPC - Games - [DSK] (TOSEC-v2021-07-25_CM)"
"Sharp X68000 - Games - [DIM] TOSEC-v2014-05-13_CM" 

and Retool currently leaves all the duplicates intact. For example:
007 - A View to a Kill (1985)(Domark)
007 - A View to a Kill (1985)(Domark)[a]

007 - Licence to Kill (1989)(Domark)
007 - Licence to Kill (1989)(Domark)[cr CACH]

1942 (1986)(Elite Systems)
1942 (1986)(Elite Systems)[t]

They also seem to use different region and language tags than No-Intro/redump that Retool also doesn't seem to understand e.g. (es) for Spain, (fr) for France languages or in caps (ES) & (FR) meaning the region.

I also think it would be great if there would be a way to prefer cracked versions (tagged [cr]) on computer sets instead of the original floppy, since early copy protection is a insane hassle if you don't have original hardware and/or manuals.

**Comment by unexpectedpanda** [comment]
I've been reluctant to add other sets, simply because Redump and No-Intro are already a decent amount of work.

While MAME is an emphatic no, TOSEC is a maybe. TOSEC's strict naming scheme makes it easier to implement at least the automated parts of Retool's title matching. Clone lists would have to be up to someone else, the set is simply too big for me to take that on by myself.

I've had a few things IRL that have kept me away from Retool of late, but the primary focus is still the rewrite for better performance and easier maintenance. After that, I can look into new capability.
