### ISSUE TITLE
N64 - Blues Brothers 2000 Europe (Beta) remains in dat

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#123]
## Dat
Nintendo - Nintendo 64 (BigEndian) (20210916-084602)

## Issue
I'm finding Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl) (Beta) (2000-01-15, Alt) in the 1G1R even though Blues Brothers 2000 (USA) is there. the non alt version might create the same issue, I'm not sure.

**Comment by unexpectedpanda** [comment]
I saw something like this recently and hoped they would correct the naming error in later releases. I suspect it's the non standard `(<DATE>, Alt)` format that's causing the problem, instead of splitting the date and the alt tags as they're meant to.

I'll wait this one out a little bit, and will add it in if it continues to cause issues.

**Comment by unexpectedpanda** [comment]
I've left a message, let's see if it gets changed. If not, I'll add it in.

**Comment by unexpectedpanda** [comment]
Looks like they're intent on messing up their own standard. I'll rework the clone list.
