### ISSUE TITLE
Feature request: language order and option to prioritize languages over regions

### ISSUE THREAD

**Issue by fedecorigliano** [unexpectedpanda/retool#126]
As a native Spanish speaker I would like to have a romset where those games that have a spanish version are selected over the other clones and after that prioritize the selected region. It would not be a filter, but an order of preference. Would it be possible?

**Comment by unexpectedpanda** [comment]
Right now regions are prioritised, followed by languages, as you've realised. This can create not great situations, where you can end up with a title that doesn't support your language (I've seen this with English too).

Language priority would be nice, however it's a decent amount of work. If it gets done, it'll go into a future rewrite of Retool.

**Comment by noinkling** [comment]
As long as this stays unimplemented, is there a workaround anyone can think of to achieve this via merging/diffing dats, etc?

For instance, you could use Retool to create a Spanish-only dat and a non-Spanish dat, then merge them in a way that anything in the Spanish dat overrides/replaces clones in the non-Spanish dat. Does tooling exist that can do that?

**Comment by noinkling** [comment]
I found that https://github.com/andrebrait/1g1r-romset-generator can prioritize languages above regions by using the `--prioritize-languages` flag, however:

1. It can't output a dat file, it can only work directly on rom files.
2. It needs a parent/clone dat to work, ruling out stuff like Redump completely (because they don't release P/C dats). It also means it can't use the extra work on clonelists that happens here.

**Comment by unexpectedpanda** [comment]
This is functional in v2. I feel comfortable saying it should be available in about a month's time.

**Comment by noinkling** [comment]
That's great to hear.

In the meantime I found out that @andrebrait's newer tool [DATROMTool](https://github.com/andrebrait/DATROMTool) can output a dat. So you can do something along the lines of:

    java -jar DATROMTool-cli-1.0.0-RC2.jar 1g1r --out-mode=xml --out-file=Spanish_Priority.dat --sort-languages=Es,En,Ja --sort-regions=MEX,ARG,USA,AUS,NZ,UK,EUR,SPA --prioritize-languages <path to P/C dat>

(trying to prioritize Latin American Spanish in this case, and deprioritize multi5+ versions)

**Comment by andrebrait** [comment]
> That's great to hear.
> 
> In the meantime I found out that @andrebrait's newer tool [DATROMTool](https://github.com/andrebrait/DATROMTool) can output a dat. So you can do something along the lines of:
> 
>     java -jar DATROMTool-cli-1.0.0-RC2.jar 1g1r --out-mode=xml --out-file=Spanish_Priority.dat --sort-languages=Es,En,Ja --sort-regions=MEX,ARG,USA,AUS,NZ,UK,EUR,SPA --prioritize-languages <path to P/C dat>
> 
> (trying to prioritize Latin American Spanish in this case, and deprioritize multi5+ versions)

Note that in DATROMTool sorting and filtering are separate options. This will only sort. For filtering, you need to add the corresponding filter options.

For now, DATROMTool relies entirely on the DAT (and ROM naming, detecting types, additional regions and languages by parsing them from the names) to do its thing, so be aware that whatever you feed to it in the DAT will be its only source of truth. 

Also, if it happens to be missing a region or it can't recognize one, you can customize a region data file and place it in its configuration folder (usually `$USER_DIR/.DATROMTool`).

**Comment by unexpectedpanda** [comment]
Well, I was wrong about "in a month's time". So close :)

v2 is now out, and recognizes language priority, it's not purely a filter. This means when Retool selects a European title, your preferred language is taken into account.

**Comment by unexpectedpanda** [comment]
I appreciate the feedback, it's good to get different perspectives. There's a lot of balance to take into account with this, and it's never going to hit everyone's preferences.

The model Retool is following is:

* I'd prefer language 1.
* I'll accept language 2 if language 1 isn't available.
* I'll accept language 3 if the first two aren't available.
* ...and so on.

This is based on the idea that people have a primary language that they prefer to use, and then secondary, tertiary, and so on. What you're asking for increases the complexity significantly in code and interface design. What's the use case for preferencing all three languages? The only thing that comes to mind is as a learning aid to strengthen those non-primary languages, assuming you play the game a second or third time.

> The current behaviour is for Retool to only regard the first (matching) language before using region priority. 

That's not quite how it works. Each region is considered individually, and within that region winners are picked based on filter criteria. The regional winners are forwarded to a global round where the final winner is chosen.

There's more steps than that, but that's the basic gist.

Within a regional run, a first language pass is performed as an early filter that looks for the highest priority language available in a set of titles for two reasons:

* To remove higher versioned titles that don't support the highest possible preferred language.
* To ensure lower-priority languages don't force a lower version selection.

For example, take the following two titles:

_GameShark CDX (USA) (Unl) (v4.11B)_
_GameShark CDX (USA) (En,Fr,Es,Pt) (Unl) (v4.1)_

Let's say you have a language priority of English, Spanish. The first title has no language specified at all, but has an implied language of English due to the region being USA. Right now Retool selects the 4.11B version, as it filters by the top language available, then by versions and other criteria, and comes back to do a full language pass later on.

If you do a full language pass before the other criteria, then v4.1 gets selected instead, as 4.11B doesn't feature Spanish. English might be your strongest language, but you get the lower version because of the other languages.

During the global round, Retool filters by language again, based on the top available language in the comparison, again attempting to preference the strongest language.
