### ISSUE TITLE
Filter by languages not optimal for different clones of the same region

### ISSUE THREAD

**Issue by Knopfdruckoffizier** [unexpectedpanda/retool#160]
## Dat
All datfiles that includes different langues clones in Europe region (i.e. En,De,Fr... vs. En,Sv,No... vs. En,Es,It...)

## Issue
A non English native speaker may prefer the Europe clone that includes his own native language beside English over sets that would only include English and other languages.
status atm:
i. e. if filtered for Languages En and De means for Europe sets you may get the clone with En,Fr instead of the existing En,De

**Comment by unexpectedpanda** [comment]
I don't have the capability to access the code base/test at the moment, but IIRC the proposed operation is how Retool works if no language filters are in place. I'm guessing since there's no sense of language priorities when language filters are used, this is resulting in the sub-optimal selection.

Languages are being reworked in Retool 2.0, so I'll slot this in with that work.

**Comment by unexpectedpanda** [comment]
v2 now pays a lot more attention to language priority. As a result, it should select European titles with your favored language.
