### ISSUE TITLE
Option to keep first release and latest release

### ISSUE THREAD

**Issue by beyondmeat** [unexpectedpanda/retool#178]
A lot of retroachievements for games will only work for the 1.0 rev of a game, sometimes it's the first release, first revision, and maybe the last rev. Typically though, I noticed the last rev lacks a lot of compatibility with them.

Is that possible with retool?

**Comment by unexpectedpanda** [comment]
Ah, I didn't know Retroachievements existed. Looks like a cool community :)

Much like #91, it's not a straightforward thing for Retool to get anything other than the latest version due to the way it's designed, especially where clone lists are involved. It'd not only be a big change to make, it would introduce a decent amount of ongoing manual work.

Since the Retroachievements system is gating by hash (albeit seemingly a custom hash based on a portion of a file), it'd be more beneficial to the Retroachievements community for them to supply DAT files directly. Having said that, there might be reasons why they haven't done so already.
