### ISSUE TITLE
Europe Titles not expected based on filter selection

### ISSUE THREAD

**Issue by updawg** [unexpectedpanda/retool#180]
**Describe the bug**
Europe only titles are being included in the output when USA/WORLD/English is selected as the filter. This also happens with USA/English with World removed.

Games that shouldn't be included:
32 in 1 Game Cartridge (Europe).zip
4 Game in One (Europe) (Bit Corporation).zip
Acid Drop (Europe).zip
Alien's Return (Europe).zip
Base Attack (Europe).zip

**To reproduce**
Run the tool with the following options on the latest No-Intro Atari 2600 dat file:
(-aAbBcdemMpPruv)

**Expected behavior**
To only receive output of USA/World/English titles.

**Operating system**
- [ ] Windows 10 

**Retool edition**
- [ ] retool-gui.exe

**Retool version**
CLI 1.5
GUI 0.11
(-aAbBcdemMpPruv)

**Are you using custom global or system filters? If so, list them below**

Global excludes: N/A

Global includes: N/A

System excludes: N/A

System includes: N/A

**What other settings are you using?**
Excluding everything but Add-Ons and Bonus Discs

**Comment by unexpectedpanda** [comment]
I can't replicate this in Retool or Retool GUI, European titles are being removed as they should. Just double checking there are no custom global or system includes?

The only other thing that immediately springs to mind is maybe Retool is in a read only folder, and `user-config.yaml` can't be updated. It's worth opening it up and checking if it updates when you change the settings in Retool GUI.

Otherwise, we have a mystery that will require further digging!

**Comment by updawg** [comment]
I feel like an idiot. I was using RomVault to manage my romsets. It was highlighting the roms because they were found in the sorted folder and shouldn't be there. I thought it was highlighting the missing roms. I apologize for making you check this out.

**Comment by unexpectedpanda** [comment]
No worries at all :)
