### ISSUE TITLE
[Feature idea/request] Platform exclusives filter 

### ISSUE THREAD

**Issue by BobbyBoyGaming** [unexpectedpanda/retool#235]
Since Retool 2.0 will now support platform-specific settings, then the next cool thing to do in my opinion would be to be able to have one platform as a main platform. 

For example say I have the entire 1G1R for PS2, but then I do want some of the Gamecube stuff, but only as long as it is unique/exclusive.

The "Exclusive releases filter" would just remove the very obviously ported stuff, it doesn't need to be a perfect filter as far as I am concerned.

**Comment by unexpectedpanda** [comment]
Cross-system 1G1R is an entirely different beast. The data model of Retool never had it in mind, meaning it's a huge project. It might need some sort of database to work effectively. It might also need to remember DATs you've loaded in the past kind of like RomVault does instead of treating them as ephemeral. You'd need to be able to prioritize specific systems as you've raised. Apart from GUIs being a pain to build, supporting these features in the CLI would be tricky, too.

It's a great idea, there's just so much work involved to make it happen. I'm going to close this for now, but if I'm ever mad enough to do a V3, it'll be in my mind.
