### ISSUE TITLE
Wii U (Digital) (CDN): Metroid - Other M

### ISSUE THREAD

**Issue by Keiyuu** [unexpectedpanda/retool#246]
## Dat
Wii U (Digital) (CDN)

## Issue
My region order for this DAT has Europe and other European countries before USA, but Retool removes the European version of Metroid - Other M and keeps the USA version.

Affected ROMs:
Metroid - Other M (Europe) (En,Fr,De,Es,It) (Wii)
Metroid - Other M (USA)

**Comment by unexpectedpanda** [comment]
I don't know what's going on here. It's going to need more investigation.

**Comment by unexpectedpanda** [comment]
Due to the `(Wii)` tag, it thinks this is a ROM ripped from a modern rerelease. Which would be true on an older platform, but obviously isn't the case here with the Wii U being newer. I *think* though this is a nomenclature problem more than a program issue.

Having said all this, this is only turning up as a problem because No-Intro has named things inconsistently here -- the USA title should really also have the `(Wii)` tag. I'll see if I can shake that particular tree.
