### ISSUE TITLE
SNES: Super Mario World is missing

### ISSUE THREAD

**Issue by SiriusVI87** [unexpectedpanda/retool#253]
**Describe the bug**
When using Retool with SNES, Super Mario World is deleted and "Super Mario All-Stars + Super Mario World (USA)" is kept instead. Is this behavior normal? 

**Expected behavior**
Shouldn't the individual titles be kept instead? Actually, I would prefer both versions to be kept in this case. Is there an option somewhere to keep both the standalone titles as well as compilations the title was included in?

In my opinion, compilations are kind of a separate game/release from the standalone games and should not replace standalone releases, not even in a 1G1R set if that makes sense. So in the example above, I would like to have:

1. Super Mario World standalone USA
2. Super Mario All-Stars standalone USA
3. Super Mario All-Stars + Super Mario World compilation USA

Wouldn't it be possible to add an option that says "keep compilations"? 

**Operating system**
Windows 11

**Retool edition**
- [x] retool-gui.exe

**Retool version**
Newest

**Comment by unexpectedpanda** [comment]
This behavior is intended. _Super Mario All-Stars + Super Mario World_ is defined as a superset instead of compilation, as for _Super Mario World_ at least the compilation [includes more features than the standalone title](https://www.mariowiki.com/Super_Mario_All-Stars_%2B_Super_Mario_World).

> Is there an option somewhere to keep both the standalone titles as well as compilations the title was included in?

No, but you can use a user filter instead to keep the titles you want.

> Wouldn't it be possible to add an option that says "keep compilations"?

There are many ways to approach compilations -- for now only one is implemented. Maybe in the future I'll add some other methods, but it's not a high priority right now.

**Comment by SiriusVI87** [comment]
OK, thanks for the clarification!

I still think that the option to keep collections that combine different games on top of the individual titles would be nice, even for a 1g1r set.

Again, I believe that collections of games, regardless of whether supersets or compilations, are their very own releases and not really clones. They come with their own physical medium, have different artwork, have a different ingame menu, and so on.
