### ISSUE TITLE
Nintendo Wii 1g1r list seems to contain multiple clones

### ISSUE THREAD

**Issue by SiriusVI87** [unexpectedpanda/retool#260]
## Dat
Nintendo - Wii (2023-04-18 21-39-09) (Retool 2023-04-26 21-39-58) (1,673) [-abBcdmpPr].dat

## Issue
I created a 1g1r rom list using the dat from redump as a source. In the list created by retool, I found several clones still remaining. Examples are:

1. Party Pigs: Farmyrad Games (USA) - Athletic Piggy Party (Europe)
2. Mercury Meltdown Revolution (USA) - Tama-Run (Japan)
3. Naruto: Clash of Ninja Revolution (USA) - Naruto Shippūden: Gekitō Ninja Taisen! EX (Japan)
4. Just Dance: Summer Party (USA) - Just Dance 2: Extra Songs (Europe)
5. The Kore Gang - The Kore Gang: Outvasion from Inner Earth
6. Active Life: Magical Carneval (USA) - Issho ni Asobu! Dream Theme Park (Japan)

These are just a few examples and there are many more. Is this a bug or am I missing something? Is there a reason these clones are included?

Thank you!
[Nintendo - Wii (2023-04-18 21-39-09) (Retool 2023-04-26 21-39-58) (1,673) [-abBcdmpPr].zip](https://github.com/unexpectedpanda/retool/files/11476039/Nintendo.-.Wii.2023-04-18.21-39-09.Retool.2023-04-26.21-39-58.1.673.-abBcdmpPr.zip)

**Comment by 0xC0D3D34D** [comment]
Are your clone lists up to date? I have already fixed the party pigs issue and it has been merged. If I get chance I'll take a look at the others in the next few hours and submit another pull request.

**Comment by SiriusVI87** [comment]
Well I created the dat on April 26, which is not that long ago. Have there been significant changes since then?

**Comment by 0xC0D3D34D** [comment]
It was merged yesterday. By the way, you'd have probably been better posting this in the clone list repo [here](https://github.com/unexpectedpanda/retool-clonelists-metadata)

**Comment by SiriusVI87** [comment]
Ah that's good to know, thank you. I was of the impression that the work on all these parent/clone relationships was already completed. In order to keep a 1g1r set clean, it would be required to check periodically if something has changed, right?

**Comment by SiriusVI87** [comment]
I've tried the updated clone file and indeed the party pigs game is now sorted correctly. However, none of the other games are.

Additionally, "Super Swing Golf Season 2" was for some reason excluded, even though it should be included in the list. This is not intedned, right?

https://wiki.dolphin-emu.org/index.php?title=Super_Swing_Golf_Season_2

**Comment by unexpectedpanda** [comment]
Cheers @0xC0D3D34D, appreciate your work :) And thanks @SiriusVI87 for the heads up!

> I was of the impression that the work on all these parent/clone relationships was already completed.

It's always a work in progress. Redump and No-Intro still update their DATs too, so it's an endless chase. Community involvement is definitely welcome. Ideally Retool would get to a point where there are specific system maintainers. There have been many invaluable contributions (shout out especially to @rufotheone-fr, @retroNUC, @0xC0D3D34D, and @Florin9doi) over its lifespan.

> Of course, I was only able to check, because I made a 1g1r set by hand a few years back.

Awesome, your expertise is appreciated.

The clones you've listed I'll look into. In the meantime, can you provide your settings so I can copy your setup? That way I can look into those individual titles more deeply, and why they were excluded. Usually attaching `config/user-config.yaml` is the easiest way. If you used system settings, then attaching `config/systems/Nintendo - Wii (Redump).yaml` is also useful.

```
"group": "Super Swing Golf Season 2",
"titles": [
  {"searchTerm": "Super Swing Golf Season 2"},
  {"searchTerm": "Swing Golf Pangya 2nd Shot!"},
  {"searchTerm": "Super Smash Bros. Brawl"}
]
```

Oof, that's a clanger. I'll get that one corrected ASAP.

**Comment by unexpectedpanda** [comment]
I've updated the clone list to include the titles you've mention except for:

> Naruto: Clash of Ninja Revolution (USA) - Naruto Shippūden: Gekitō Ninja Taisen! EX (Japan)

I need to do more digging on it, as I can only find [one reference](https://naruto.fandom.com/wiki/Naruto:_Clash_of_Ninja_Revolution) which suggests it's a bit of a hybrid, and fighting games can get complex.

**Comment by 0xC0D3D34D** [comment]
I don't think its a variant, just shares the engine
[see here](https://web.archive.org/web/20120229150227/http://wii.ign.com/articles/793/793355p1.html)

**Comment by SiriusVI87** [comment]
> @unexpectedpanda you're correct about Just Dance 2, I didn't read it properly. I thought it was saying it contained the content of JD2 and the DLC (most of).
> 
> I wonder whether for a 1g1r set any version with a unique track should be kept. I can see reasons for and against.
> 
> Have to agree the music games seem a PITA.

Yeah extremely difficult. However, in other cases regional variations are usually not kept. Best examplenis Contra / Super Probotector on SNES. The European Version turns the main characters into robots. Ist this a big enough change that warrants its inclusion in a 1g1r romset?

There is no clear answer here I guess. With Song games, I think if a substabtial amount of songs are different, the different versions should be kept.

**Comment by unexpectedpanda** [comment]
> I wonder whether for a 1g1r set any version with a unique track should be kept. I can see reasons for and against.

Historically I kept titles with unique tracks, but I recall the Singstar series in PS2 being grouped together by a few different contributors. I figured at the time your average English-speaker isn't going to sing along with Dansk tracks... but vice-versa certainly isn't true and that decision is probably going to need to be revisited in the future.

> Yeah extremely difficult. However, in other cases regional variations are usually not kept. Best examplenis Contra / Super Probotector on SNES. The European Version turns the main characters into robots. Ist this a big enough change that warrants its inclusion in a 1g1r romset?

For Retool, sprite swaps, palette changes, or texture changes are generally considered clones if the gameplay remains largely the same. For example, there are quite a few Game Boy games that are identical save for the sprites, as there were different licensing deals done in different countries for specific cartoon characters. They're considered clones. There are also a few PlayStation games that are just retextures with a few different models, but otherwise things are the same. For a specific example, _V-Ball - Beach Volley Heroes_ and _Chou Sentou Kyuugi Vanborg_ for PlayStation are considered clones, even though there's [unique content between them](https://github.com/unexpectedpanda/retool/issues/204#issuecomment-1164302194), as they are still functionally just reskins -- the unique volleyball courts don't really change the experience in any measurable way.

There's always a blurry line which means titles have to be assessed on a case-by-case basis, but the general rule of thumb is: does it impact gameplay in a meaningful way (new levels, different ways of interacting)? If so, there's a chance it's a unique title. That can break down for things like fighting games where each variation makes refinements to balance (and there's a vocal crowd of people claiming that every change is meaningful due to competition use of such games), but overall it works reasonably well as a rubric.

Another guiding star for me: the point is to only have one copy of a title. If you only had time to play one version of this game, which would it be? If you're going to include more than one, you're heading down the slippery slope of hoarding again, so that extra title better be included for a very good reason.

**Comment by unexpectedpanda** [comment]
> Anyway, here are my files.
[Retool Files.zip](https://github.com/unexpectedpanda/retool/files/11483795/Retool.Files.zip)

Thanks, but I think you've included the wrong files -- I already have the clone list locally and the DAT. I need the following files to learn about your configuration:

* `config/user-config.yaml`
* `config/systems/Nintendo - Wii (Redump).yaml`

**Comment by SiriusVI87** [comment]
Sorry for the wrong files. This file does not exist for me: config > systems folder: Nintendo - Wii (Redump).yaml`

But I can send you the other file. 
[user-config.zip](https://github.com/unexpectedpanda/retool/files/11488848/user-config.zip)

**Comment by unexpectedpanda** [comment]
No worries, that just means you didn't create a system config, which makes debugging easier for me :)

**Comment by unexpectedpanda** [comment]
Here's my results using the configuration you provided.

## Other titles selected due to user config
* `Metroid Prime (Japan)`: `Metroid Prime Trilogy (USA)` chosen instead because it supports English, which is higher up your implied language order (USA ranked higher than Japan, so English is higher than Japanese).
* `Metroid Prime 2 - Dark Echoes (Japan)`: `Metroid Prime Trilogy (USA)` chosen instead because it supports English, which is higher up your implied language order (USA ranked higher than Japan, so English is higher than Japanese).
* `Little League World Series Baseball 2008 (USA)` & `Little League World Series Baseball 2009 (USA)`: `Little League World Series Baseball - Double Play (USA)` chosen instead because it was marked as a superset of the individual titles. I think this is an error, and I've converted this to a compilation. With the update, the individual titles are selected instead.
* `Namco Museum Remix (USA)`: `Namco Museum Megamix (USA)` chosen instead, as it's a [superset of this title](https://en.wikipedia.org/wiki/Namco_Museum_Remix) that has more content.
* `My Pet Hotel (Europe) (En,Fr,De,Es,It)`: `Paws & Claws - Pet Resort (USA)` chosen instead, as USA is higher up your region order than Europe.
* `Imagine - Champion Rider (Europe) (En,Fr,De,Es,It,Nl)`: `Petz - Horse Club (USA)` chosen instead, as USA is higher up your region order than Europe.
* `Chiffres & Des Lettres, Des - Le Jeu Officiel (France)`: `Countdown - The Game (Europe)` chosen instead, as it supports English, which is higher up your implied language order.
* `Babysitting Party (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da)`: `Imagine - Party Babyz (USA) (En,Fr,Es)` chosen instead, as USA is higher up your region order than Europe.
* `uDraw Studio (USA) (En,Fr,Es)`: You opted to remove applications. Redump has classified this as an application, but the European version as a game. I've overridden this in a newer version of the clone list so they're all games.

## Titles that are in the output DAT with your configuration

I'm not sure why these are in the list. These all make it to the output DAT on my machine.

* `Quiz Party (UK)`: This is included in the output DAT for your configuration. The French and German clones are removed.
* `Lucha Libre AAA - Heroes del Ring (Latin America) (En,Es)`: This is included in the output DAT for your configuration. It has no clones.
* `Thomas & Friends - Hero of the Rails (UK)`: This is included in the output DAT for your configuration. The Scandinavian clone is removed.
* `My Spanish Coach - Improve Your Spanish (UK)`: This is included in the output DAT for your configuration. It has no clones.
* `Springdale (Scandinavia) (En,Sv,No,Da,Fi)`: This is included in the output DAT for your configuration. It has no clones.
* `Top Trumps - Doctor Who (UK)`: This is included in the output DAT for your configuration. It has no clones.
* `Peppa Pig - Fun and Games (UK)`: This is included in the output DAT for your configuration. It has no clones.
* `Golden Balls (UK)`: This is included in the output DAT for your configuration. It has no clones.
* `G1 Jockey Wii 2008 (UK)`: This is included in the output DAT for your configuration. The Japanese clone is removed.
* `G1 Jockey Wii (UK)`: This is included in the output DAT for your configuration. The Japanese clone is removed.
* `Family Fortunes (UK)`: This is included in the output DAT for your configuration. It has no clones.
* `Doctor Who - Return to Earth (UK)`: This is included in the output DAT for your configuration. It has no clones.
* `Ready Steady Cook - The Game (UK)`: This is included in the output DAT for your configuration. The French and Italian clones are removed.
* `Chavo, El (Latin America) (En,Es,Pt)`: This is included in the output DAT for your configuration. It has no clones.
* `Super Swing Golf Season 2 (USA)`: This is included in the output DAT for your configuration. The European, Japanese, and Korean clones are removed.
* `Ashes Cricket 2009 (UK)`: This is included in the output DAT for your configuration. The Australian clone is removed.
* `Atrevete a Sonar (Latin America) (En,Es)`: This is included in the output DAT for your configuration. It has no clones.

**Comment by SiriusVI87** [comment]
Hey, thank you so much for your feedback. i just tried again and now all the items are included. I don't know what I did wrong at first, but I'm sure I messed up somewhere.

Thank you!

**Comment by unexpectedpanda** [comment]
Cool, I'll close this out then. Feel free to file another issue if you find missing clones :)
