### ISSUE TITLE
TurboGrafx-16 / CD Incorrect Language Filter

### ISSUE THREAD

**Issue by pascalfco** [unexpectedpanda/retool#275]
**Describe the bug**
- Retool seems to be having a hard time applying language filters to both the TurboGrafx-16 and TurboGrafx-CD platforms.

**To reproduce**
- Filter by region should include Japan and Filter by language order should start with English.
- Unfortunately for the time being English Japanese titles are getting removed.
- This has been counter-verified by generating an English-only DAT file from the No-Intro DAT-O-Matic web site.

**Expected behavior**
- English Japanese titles should not be removed from the set.

**Operating system**
- [ X ] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [ X ] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
- 2.01.1

**Are you using custom global or system filters? If so, list them below**

Global excludes:
- Applications
- Bad Dumps
- BIOS and other chips
- Demos, kiosks and samples
- Pirate
- Preproduction
- Promotional
- Unlicensed

**Comment by unexpectedpanda** [comment]
When I download `NEC - PC Engine - TurboGrafx-16 (20230718-134255).dat` from Dat-O-Matic and filter by Japan and English only, I get three titles in the downloaded DAT:

* Final Soldier (Japan) (En)
* Final Soldier - Special Version (Japan) (En)
* Splatterhouse (Japan) (En)

When I run the full DAT through Retool with your settings, I get two titles in the downloaded DAT (because one is removed as a duplicate):

* Final Soldier (Japan) (En)
* Splatterhouse (Japan) (En)

The titles still remain if I add more languages after English. Digging into the metadata and ignoring the `(En)` tag, it looks like these are the only titles marked as supporting English in the No-Intro database.

I get a similar experience with `Non-Redump - NEC - PC Engine CD + TurboGrafx CD (20230628-083646).dat`. Filtering by Japan and English only on Dat-O-Matic gets me three titles:

* Angels 2 - Holy Night (Japan) (En) (Proto)
* Force Gear (Japan) (En) (PC Engine mini)
* Space Fantasy Zone (Japan) (En) (Proto)

With your settings, Retool removes the two protos to get:

* Force Gear (Japan) (En) (PC Engine mini)

One thing I got caught by on Dat-O-Matic, is you need to click the **Custom** radio button when selecting regions and languages, not just the region/language itself, or the filter doesn't apply:

![nec-turbografx-16](https://github.com/unexpectedpanda/retool/assets/15709984/b574b444-fefa-4b7c-a8fb-1da2606110c4)

Let me know if I've misunderstood, or if you're still seeing something different from me.

**Comment by pascalfco** [comment]
You are completely right, I got caught as well by the Custom radio buttons not being selected properly.

After some additional digging, I was able to generate separate TurboGrafx-16 DAT files with English, Japanese and nolang filters. I was hoping nolang might be it, but alas it did not solve the issue.

The main problem seems to be coming from the fact that neither No-Intro nor Redump treat and name Japanese English titles properly.

Take AfterBurner II (Japan) for example, this title is clearly in English but it has been catogerized as being in Japanese by No-Intro.

My main objective when creating 1G1R sets would be to keep all of the English titles from Japan especially when these were exclusive titles.

Let me know if an idea comes to mind. Would there be a way to counter-validate title languages from a different source instead ?

Worst comes to worst I could always reach out to both release groups to try and have the DATs corrected.

**Comment by unexpectedpanda** [comment]
I think the unfortunate answer is it needs to be [fixed at the source](https://unexpectedpanda.github.io/retool/contribute-metadata-files/).

A heads up if you do file tickets at No-Intro: some system maintainers can be strict about only marking something as an English title if it's 100% in English. It depends who you hit. AFAIK there isn't an "English friendly" attribute.

Some people have asked for Retool to essentially keep its own language database to overcome this, but it's not feasible to maintain as just me. In terms of automating the task, there are quite a few game databases around -- but none that I'm aware of that can be relied upon as a secondary source for language-per-system release details.

In the interim I think the best bet for reaching your goal is a web search. There are a few lists on the internet for "English friendly" TurboGrafx-16 games that could be cross-referenced with an exclusive games list. Sadly this means much slower manual curation.

I'll close this up now as it's not something Retool can address -- but I definitely hope it gets fixed at the source one day.
