### ISSUE TITLE
System-specific language overrides wrongly affecting results

### ISSUE THREAD

**Issue by Keiyuu** [unexpectedpanda/retool#276]
**Describe the bug**
I'm using the PlayStation DAT to produce a Germany region Demos-only set.
I noticed multiple Demos are missing from the resulting DAT and it took me a while to figure out the culprit is the system-specific language setting. Since I use English and Japanese as the global setting, I checked "Override global settings" on the languages tab under System settings and used an empty list (to include all potential languages). This results in Retool removing multiple demos:

- Crime Killer (Germany) (Demo)
- Demo One (Version 4) (Germany)
- Fluid (Germany) (Demo)
- MIP Club Demo 01 (Germany)
- Next Wave Herbst '98 (Germany)
- Resident Evil (Germany) (Demo)
- Silent Hill (Germany) (Demo)
- VIP Demo (Germany)

These are the ones I caught. All of them are in the "Demos" category in Redump.
If I uncheck the system override for languages and set global languages to an empty list, they are included.

**To reproduce**
- Use Redump's PlayStation DAT
- Override global region settings and select Germany only
- Override global language settings and leave the list empty
- On Exclusions tab override global settings and check everything except "Demos, kiosks, and samples"

**Expected behavior**
All Germany region Demos to be included in the DAT

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
2.01.1

**Additional context**
Likely unrelated but Retool also removes the different German versions of "Demo One" and only keeps "Demo One (Version 4)" despite them all being different. There might be more occasions but this is what I caught so far.
I don't think this behavior is desired since Demo discs are usually all unique and not _upgrades_ of each other.
http://redump.org/disc/47282/
http://redump.org/disc/46256/
http://redump.org/disc/1038/

**Comment by unexpectedpanda** [comment]
Looks like more than demos are getting lost. That's definitely not ideal, I'll look into it.

> Likely unrelated but Retool also removes the different German versions of "Demo One" and only keeps "Demo One (Version 4)" despite them all being different. There might be more occasions but this is what I caught so far.
I don't think this behavior is desired since Demo discs are usually all unique and not upgrades of each other.

You're correct, the goal is keeping titles that are unique, and yes, it's unrelated to the other issue. The problem here is generalized detection of versions when the naming systems in play are inconsistent or not well followed. There also isn't a concept of tagging build versions in a way that's unique to, say, a variation of a title or something with "version" or "V2" literally in the name.

This is why titles like _Mobile Suit Gundam - Version 2.0_ and _Micro Machines V4_ have exceptions in clone lists: to stop them being swept up in the version detection and bundled with the wrong group of titles as different iterations. The PlayStation demos you've mentioned here would need the same treatment.

**Comment by unexpectedpanda** [comment]
Fixed in 2.01.2.

**Comment by Keiyuu** [comment]
I just tried the new version 2.01.3 and it's still bugged. 
Now it's reversed. It keeps the Demos I mentioned above but removes everything else, resulting in only 11 Demos in the DAT.

**Comment by unexpectedpanda** [comment]
That's odd -- it was working before I pushed out the change. I'll take another look.

**Comment by unexpectedpanda** [comment]
Okay, one more shot. 2.01.4 should put this one to bed. Let me know if you're still seeing unexpected behavior.

**Comment by Keiyuu** [comment]
The new version fixed it. Thanks!
