### ISSUE TITLE
A Few results that question me

### ISSUE THREAD

**Issue by Jaylinx** [unexpectedpanda/retool#320]
I just made a new scan with latest No-Intro DATS, region order is by default, in exclusion tab, everything is ticked except for "Games" and "Preproduction". The rest is untouched.

Preferred titles ripped for modern rereleases is unticked, so I expected only roms from original hardware in my 1G1R list. However, I found a few results that looks strange. In first the result from the scan and in second the result expected (or not!)

NES

Babel no Tou (Japan) (En) (Rev 1) (Namco Collection) > Babel no Tou (Japan)
Dragon Buster II - Yami no Fuuin (USA, Europe) (Namco Museum Archives Vol 2) > Dragon Buster II - Yami no Fuuin (Japan)
EarthBound Beginnings (USA, Europe) (Virtual Console) > Mother (Japan)
Rockman 2, III, IV, V, VI (Taiwan) (En) (Rockman 123) > Clones from Mega Man?
Super Xevious - Gump no Nazo (USA, Europe) (Namco Museum Archives Vol 2) > Super Xevious - Gump no Nazo (Japan)
Warpman (Japan) (En) (Rev 1) (Namcot Collection) > Warpman (Japan)

PCE

Darius Alpha (World) (SG Enhanced) (Darius Cozmic Collection) > Darius Alpha (Japan) (SG Enhanced)
Bomberman '94 (World) (Wii U Virtual Console) > Bomberman '94 (Japan)

SNES

Magical Drop II (USA, Europe) (Switch Online) > Magical Drop 2 (Japan)
Star Fox 2 (Japan) (Beta) (1994-12-28) (CES) > Star Fox 2 (USA, Europe) (Classic Mini, Switch Online) is already in my DAT, is that a different game?
Star Glider (Japan) (Beta) (1992-09-23) > Star Fox (USA) (Rev 2) is already in my DAT, is that a different game?
Trials of Mana (World) (Rev 1) (Collection of Mana) > Seiken Densetsu 3 (Japan)

MD

Dyna Brothers 2 Special (Japan) (Virtual Console) > Dyna Brothers 2 (Japan)
F-22 Interceptor (USA) (1991-09-17) (Sega Channel) > F-22 Interceptor - Advanced Tactical Fighter (USA, Europe) (F-202)
Micro Machines - Military (Europe) (Beta) (1995) > Micro Machines - Military (Europe) (J-Cart)
Monster World IV (USA) (Genesis Mini) > Monster World IV (Japan)
Pebble Beach Golf Links (USA) (Rev A) (1994-02-14) (Sega Channel) > Pebble Beach Golf Links (USA)

Sonic The Hedgehog 2 (World) (Beta) (~1992-06-xx)
Sonic The Hedgehog 2 (World) (Beta) (~1992-07-xx)
Sonic The Hedgehog 2 (World) (Beta) (~1992-09-xx)
These 3 Beta versions appears while Sonic The Hedgehog 2 (World) (Rev B) is already there.

In a lot of these games, I know that region option is respected, for example Super Xevious - Gump no Nazo (USA, Europe) (Namco Museum Archives Vol 2) over Super Xevious - Gump no Nazo (Japan). USA is over Japan based on my settings, But I unticked "Preferred titles ripped for modern rereleases", so should (Namco Museum Archives Vol 2) be considered modern release and Super Xevious - Gump no Nazo (Japan) the release from the original hardware?

Last question about Sonic 1 on MD, why these lines on the json ?

					_"searchTerm": "Sonic The Hedgehog",
					"filters": [
						{
							"conditions": {
								"matchRegions": ["Japan"]
							},_

With these lines, Sonic The Hedgehog (Japan, Europe, Korea) (En) is always preferred to Sonic The Hedgehog (USA, Europe). Is there a reason ?

Thanks !

**Comment by unexpectedpanda** [comment]
> Babel no Tou (Japan) (En) (Rev 1) (Namco Collection) > Babel no Tou (Japan)
> Dragon Buster II - Yami no Fuuin (USA, Europe) (Namco Museum Archives Vol 2) > Dragon Buster II - Yami no Fuuin (Japan)
> EarthBound Beginnings (USA, Europe) (Virtual Console) > Mother (Japan)
> Super Xevious - Gump no Nazo (USA, Europe) (Namco Museum Archives Vol 2) > Super Xevious - Gump no Nazo (Japan)
> Warpman (Japan) (En) (Rev 1) (Namcot Collection) > Warpman (Japan)
> Darius Alpha (World) (SG Enhanced) (Darius Cozmic Collection) > Darius Alpha (Japan) (SG Enhanced)
> Bomberman '94 (World) (Wii U Virtual Console) > Bomberman '94 (Japan)
> Magical Drop II (USA, Europe) (Switch Online) > Magical Drop 2 (Japan)
> Monster World IV (USA) (Genesis Mini) > Monster World IV (Japan)
> Trials of Mana (World) (Rev 1) (Collection of Mana) > Seiken Densetsu 3 (Japan)

>In a lot of these games, I know that region option is respected, for example Super Xevious - Gump no Nazo (USA, Europe) (Namco Museum Archives Vol 2) over Super Xevious - Gump no Nazo (Japan). USA is over Japan based on my settings, But I unticked "Preferred titles ripped for modern rereleases", so should (Namco Museum Archives Vol 2) be considered modern release and Super Xevious - Gump no Nazo (Japan) the release from the original hardware?

Retool has to manage multiple competing priorities. In many cases, the options you set are preferences that can influence the outcome, but aren't hard rules. The result is determined by how heavily each priority is weighted internally.

Because you've ranked USA above Japan, Retool infers your preferences are for English titles over Japanese. Since language preferences are checked very early in the process, and the modern editions are the only ones that explicitly or implicitly support English, they are selected regardless of the _modern rereleases_ checkbox state.

If the titles from Japan actually support English and No-Intro hasn't included that data, that can be set in the clone lists with the `englishFriendly` key, which changes the selection bias.

Others have already expressed interest in providing more options for modern edition handling, but that's a way off yet.

> Pebble Beach Golf Links (USA) (Rev A) (1994-02-14) (Sega Channel) > Pebble Beach Golf Links (USA)

It's a higher revision, so it gets selected. Sega Channel isn't considered a modern rerelease.

> Rockman 2, III, IV, V, VI (Taiwan) (En) (Rockman 123) > Clones from Mega Man?

This is new, so hasn't been included in the clone lists yet.

> Star Fox 2 (Japan) (Beta) (1994-12-28) (CES) > Star Fox 2 (USA, Europe) (Classic Mini, Switch Online) is already in my DAT, is that a different game?

It's been missed due to the `(CES)` tag, and needs to be added to the clone list.

> Star Glider (Japan) (Beta) (1992-09-23) > Star Fox (USA) (Rev 2) is already in my DAT, is that a different game?

This needs to be added to the clone list.

> Dyna Brothers 2 Special (Japan) (Virtual Console) > Dyna Brothers 2 (Japan)

`Dyna Brothers 2` has been set with a lower priority in the clone list as it contains less content.

```
Dyna Brothers 2... later had an expanded version exclusive for the Sega Channel in 1995 and that version later re-released for the Wii.
```

[Source](https://nintendo.fandom.com/wiki/Dyna_Brothers_2)

> F-22 Interceptor (USA) (1991-09-17) (Sega Channel) > F-22 Interceptor - Advanced Tactical Fighter (USA, Europe) (F-202)

Genuinely no idea, I don't remember this and I can't find any evidence online as to why it should be this way. Looks like the F-202 and F-205 just come from a chip serial, so this can probably be changed,.

> Micro Machines - Military (Europe) (Beta) (1995) > Micro Machines - Military (Europe) (J-Cart)

Both of these titles are included because of the `(1995)` tag (yet another date format from No-Intro). It needs to be added to the clone list.

> Sonic The Hedgehog 2 (World) (Beta) (~1992-06-xx)
> Sonic The Hedgehog 2 (World) (Beta) (~1992-07-xx)
> Sonic The Hedgehog 2 (World) (Beta) (~1992-09-xx)

This is a combination of two things: these are newly added to the DAT file so the clone lists haven't been updated to take them into account, and once again No-Intro has managed to make up an entirely new date format, as they use free text fields and not validated date fields.

> With these lines, Sonic The Hedgehog (Japan, Europe, Korea) (En) is always preferred to Sonic The Hedgehog (USA, Europe). Is there a reason ?

Yes. Sonic Japan is a newer build that features additional parallax scrolling in the backgrounds, and so is treated as a superset.

**Comment by Jaylinx** [comment]
Thanks for all these explanations. I'm still digging to find some other missing clones !

**Comment by unexpectedpanda** [comment]
Clone lists have been updated.
