### ISSUE TITLE
Elite Beat Agents - Osu! Tatakae! Ouendan

### ISSUE THREAD

**Issue by Freeben666** [unexpectedpanda/retool#37]
## Dat
No-Intro - Nintendo - Nintendo DS

## Issue
"Elite Beat Agents" and "Osu! Tatakae! Ouendan" are similar games, the former being the occidental version of the latter, but they have different songs, and so should be considered different games.

**Comment by unexpectedpanda** [comment]
Looks like Elite Beat is a quasi-kinda-spiritual-sequel as well... so, slightly evolved engine, similar experience, different content. Good call, I'll split those titles apart.

Usually I'm wary of splitting rhythm/music titles, as it seems they all have *slightly* different content per region, and that could lead back to a completionist mindset instead of 1G1R. This one makes sense though.

**Comment by unexpectedpanda** [comment]
The DS clone list has been updated.

**Comment by Freeben666** [comment]
Thank you 👍
