### ISSUE TITLE
Missing Disc 2

### ISSUE THREAD

**Issue by Freeben666** [unexpectedpanda/retool#39]
## Dat
[Nintendo - GameCube - NKit GCZ](https://dats.site/getcustdat.php?custdatid=2)

## Issue
With region selection

1. France
2. Europe
3. World
4. Unknown

And language filter: English + French

Input DAT has:

- 2 Games in 1 - Bob L'eponge - Le Film + Tak 2 - Le Sceptre des Reves (France) (Disc 1) (Bob L'eponge - Le Film)
- 2 Games in 1 - Bob L'eponge - Le Film + Tak 2 - Le Sceptre des Reves (France) (Disc 2) (Tak 2 - Le Sceptre des Reves)

Output DAT only has Disc 1

**Comment by Freeben666** [comment]
This DAT is based off the redump GC DAT, but instead of the CUE/BIN or ISO format, the discs are in the NKit.GCZ format (which saves space)

**Comment by unexpectedpanda** [comment]
Disc 2 isn't included because it's a clone of _Nickelodeon Tak 2 - Le Sceptre des Reves_. Currently Retool's clone lists preference individual titles over those included in compilations/collections.

I'm seeing signs that this needs to change, though, and that I need to rethink how compilations are handled as a whole (which is why #20 is still open). Things get messy and complex cross-region (let alone with custom region priorities), so it'll require some careful thinking and work to get the best results. It'll be a while until I can make these changes.

**Comment by unexpectedpanda** [comment]
Fixed as of 0.89.
