### ISSUE TITLE
older ROM is favored

### ISSUE THREAD

**Issue by AlvaroBurnett** [unexpectedpanda/retool#6]
When processing Game Boy ROMs, using the default regions order and English language,

Donkey Kong (Japan, USA) (SGB Enhanced)

is favored over:

Donkey Kong (World) (Rev 1) (SGB Enhanced)

**Comment by unexpectedpanda** [comment]
Howdy!

This is working as intended, as version selection is done on a regional basis. For example, in the default region order USA is ranked higher than World. Because USA is ranked higher, Retool will select the highest available version within USA, not the highest available version across all regions.

This might seem counter-intuitive at first, but it's for a good reason -- version updates tend to be directly linked to their specific region. For example, a title in Germany might have needed a language fix that wasn't required in the USA version.

I expect occasionally there'll be exceptions to this rule -- and situations like `(World)` vs `(Japan, USA)` are a little hazy (changes to 50Hz code or language updates for Europe perhaps?) -- but for the most part, that's how things operate.

**Comment by AlvaroBurnett** [comment]
Howdy! Thanks for the explanation. I wish we could know the manufacturing date of each cartridge. That way, we could take the newest of the two and not risk missing on any useful improvements that they might have forgotten to release on the other region. But I guess that we will never have that information.

**Comment by unexpectedpanda** [comment]
Likewise -- unfortunately we don't have that information at this point in time -- and I'd imagine curating it is a bigger job than dumping a cartridge. Maybe at some point in the future :)
