### ISSUE TITLE
Missing titles in output DATs since switching from 0.88 to 0.91

### ISSUE THREAD

**Issue by Freeben666** [unexpectedpanda/retool#64]
## Dat
REDUMP : Arcade - Namco - Sega - Nintendo - Triforce - Datfile (22) (2021-02-04 16-43-40).dat
(and several others)

## Issue
Settings:
- Regions: France>Europe>World>Unknown
- Languages: English + French
- Exclusions: None
- Modes: None
- Custom global filters: Include "Ouendan"

Several titles that where previously in output DATs with these setting are not present anymore

For example, with 'Arcade - Namco - Sega - Nintendo - Triforce - Datfile (22) (2021-02-04 16-43-40).dat' and my settings you'd expect 2 titles in the output DAT:
- Virtua Striker 2002 (World)
- Virtua Striker 4 (World)

But with v0.91 no output DAT is created since everything is filtered out

[Arcade - Namco - Sega - Nintendo - Triforce - Datfile (22) (2021-02-04 16-43-40).zip](https://github.com/unexpectedpanda/retool/files/6334025/Arcade.-.Namco.-.Sega.-.Nintendo.-.Triforce.-.Datfile.22.2021-02-04.16-43-40.zip)

**Comment by unexpectedpanda** [comment]
I've tested this particular dat in 0.88 and 0.91 with your settings, both versions report no titles found for me. Then it dawned on me &mdash; I added Redump metadata for additional systems recently.

Redump marks both these titles as Japanese only:

http://redump.org/disc/55301/
http://redump.org/disc/67551/

Those titles are filtered out because we now have a language for them, and they aren't English or French -- at least, according to Redump.

**Comment by Freeben666** [comment]
Hello,

Thanks for the quick response !

I did use to get a DAT with those two titles in 0.88. But if they are Japanese only, then I'm OK with not having them in the output :)

We can close this issue. Thank you for your work 👍

**Comment by unexpectedpanda** [comment]
No worries!

Yep, totally makes sense that you'd get those two titles. The metadata for Triforce was only uploaded 8 days ago, so it's likely it wasn't on your system. You'd get the same result in 0.91 if you deleted the appropriate .json file in `metadata/`.
