### ISSUE TITLE
SEGA - Master System - An elimination is here but it's tricky??

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#68]
Having this rom....
+ Marksman Shooting & Trap Shooting & Safari Hunt (Europe)

Eliminates these 2...
	- Marksman Shooting & Trap Shooting (USA, Brazil)
	- Hang-On & Safari Hunt (USA)

and vice versa

Having these 2 roms...
+ Marksman Shooting & Trap Shooting (USA, Brazil)
+ Hang-On & Safari Hunt (USA)

Eliminates this rom...
	- Marksman Shooting & Trap Shooting & Safari Hunt (Europe)

Following the the default order for english speaking in retool then the former would be applied. Eliminating the (Europe) rom.
*retool currently keeps all 3 of these roms*

**Comment by unexpectedpanda** [comment]
Yeah compilations make things hard, as it's not always a 1:1 in terms of matching titles. I've been putting off work in GBA for this very reason.

If you're still seeing all three titles you've listed, it suggests you're running an old version of Retool and old clone lists. 0.89 was built specifically to tackle this, so if you haven't already, grab the latest version of Retool and the newest clone lists, and you should see this issue go away. If not, then I'll need to probe deeper into what's happening.

As a side note, this particular situation is even more complex than described due to other compilations that don't quite match up &mdash; you also have to take into account _Astro Warrior_, _Pit Pot_, a bunch of different _Hang On_ titles, and _Fushigi no Oshiro_, which quickly gets messy between USA, Europe, and Japan depending on region order.

I built a spreadsheet to resolve this, and to my knowledge SMS is in the best condition it can be to not lose games, even though there's occasional duplication depending on region order. If you check out the relevant clone list, it's filled with removes and conditional overrides for these titles, meaning some are outright removed regardless of region order, and others have their relationships changed depending on what region is ranked higher than another.

Let me know how you go.

**Comment by unexpectedpanda** [comment]
Adding another post here to check that this is resolved?

**Comment by unexpectedpanda** [comment]
Closing this, as I believe it's no longer an issue.
