### ISSUE TITLE
Beta-roms are incorrectly prioritized over full releases

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#69]
Okay, this is just weird. 

For some reason when using the latest Retool on e.g. Redump.org's latest Sega CD -datfile, there are two Betas that override the full releases.

The roms are:
_Make My Video - INXS (USA) (Beta)
Make My Video - Marky Mark and the Funky Bunch (USA) (Beta)_

In the original datfile, you can find the full releases:
_Make My Video - INXS (Europe)
Make My Video - Marky Mark and the Funky Bunch (USA)_

But yeah, not only that. Both of these are categorized as Multimedia in the original datfile. I'm using the Multimedia filter on, but not Preproduction... **Now that I'm thinking about it, that might actually be the issue - Retool doesn't care what type is it categorized originally in the database if it fits the Preproduction -filter through filename only(?)**

Here's the full output with my settings:
[Sega - Mega CD & Sega CD (2021-04-09 19-06-16) (Retool 2021-04-23 18-31-34) (169) (-aABcdDemMov).txt](https://github.com/unexpectedpanda/retool/files/6366451/Sega.-.Mega.CD.Sega.CD.2021-04-09.19-06-16.Retool.2021-04-23.18-31-34.169.-aABcdDemMov.txt)

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
Retool GUI: 0.10
Retool CLI: 0.91

**Comment by unexpectedpanda** [comment]
If I understand correctly, all the listed titles are categorized as multimedia, and you selected to exclude multimedia. So it's not so much a case of preproduction titles being ranked above production, but multimedia titles being left in the output dat.

You're spot on about the category reclassification, which is the issue here. Early on, Retool looks for preproduction strings and reassigns category based on that. This is mainly to compensate for No-Intro, which doesn't use category tags. The same thing happens for applications, demos, and videos.

At the heart of the issue I think is that the established standard only uses one category. I can possibly work around this by adding new categories instead of replacing them, then filtering against all category tags. I'll take a look for 0.92.

**Comment by unexpectedpanda** [comment]
Looks like Redump categorizes the betas as preproduction in their dat, which is the source of the issue. Short of keeping a manual list, I don't think I can work around this.

**Comment by prklx2** [comment]
Oh shoot. You're correct. 
Didn't even notice Redump uses the Preproduction-category for all of their betas, even though the full release is categorized as something else.

Yeah, this is an issue with the dat itself, and can't be fixed on Retools end without making custom rules...


I think you should still investigate the filter logic, so that it first filters out with the datfile-categories with Redump dats and only after that it would use the filename-based filtering - if it already doesn't work that way. Just to make sure.

**Comment by unexpectedpanda** [comment]
It already works like that :) These sorts of exclusions are done during the parsing of the XML, so many titles don't even make it into consideration for later processing.

**Comment by prklx2** [comment]
Closing this issue now, since this doesn't need any fixing on Retools end.

Problem is with datfile and how Redump.org gives Preproduction -category to any rom, even though the original is categorized as Multimedia etc.

**Comment by unexpectedpanda** [comment]
Corrected in 0.92 when it's released.
