### ISSUE TITLE
Fix Retool GUI font scaling for 4k resolutions

### ISSUE THREAD

**Issue by MaXGitteR** [unexpectedpanda/retool#9]
Please fix the font or scaling in retool for 4K resolutions.

![ReTool_4k](https://user-images.githubusercontent.com/75198062/100536188-14d7e400-321f-11eb-98a6-8a035615755f.JPG)
![ReTool_fullhd](https://user-images.githubusercontent.com/75198062/100536189-15707a80-321f-11eb-9cc8-afd85ba54af2.JPG)

**Comment by unexpectedpanda** [comment]
Well that doesn't look good. Sadly this has a few things getting in the way of a resolution:

1. The module being used to build the GUI is called PySimpleGUIQt. I'm reasonably sure it doesn't support high DPI displays out of the box, given its parent project, PySimpleGUI, [doesn't](https://github.com/PySimpleGUI/PySimpleGUI/issues/1907). I'd have to look into if it can be extended by making native Qt calls.
1. Retool has been compiled to an exe using Pyinstaller. I'm not sure if this gets in the way of [setting the scaling method per application](https://www.windowscentral.com/how-change-high-dpi-settings-classic-apps-windows-10-april-2018-update) using Windows because a command prompt is loaded first instead of a GUI.
1. Most importantly &mdash; I don't have a 4k monitor to test any of these things.

I'll keep this issue open, but I can't promise a timeline on it as there's some pretty big hurdles to overcome.

**Comment by unexpectedpanda** [comment]
I've done a fair bit of work here to get Retool GUI working with font scaling in Windows. There might still be further tweaks needed, but as long as you're running Windows 10, it should look good from Retool 0.87 onward. Barring any unexpected events, 0.87 should be out soon.

**Comment by PySimpleGUI** [comment]
> I'm reasonably sure it doesn't support high DPI displays out of the box, given its parent project, PySimpleGUI, doesn't. I'd have to look into if it can be extended by making native Qt calls.

I use three 4K UHD TVs as my monitors on my PC.  I dunno if I would go so far as to say that PySimpleGUI doesn't support high res displays.

![image](https://user-images.githubusercontent.com/46163555/135355607-3dd33ec3-5db5-4614-bad0-7f2f551ca545.png)

I am interested in your project participating in the upcoming Alpha of the 1.0 release of PySimpleGUIQt.

I'm not sure if your project uses PySimpleGUIQt anymore though.  I don't see anything in the repo other than in the Wiki and this issue.

**Comment by unexpectedpanda** [comment]
Howdy!

> I use three 4K UHD TVs as my monitors on my PC. I dunno if I would go so far as to say that PySimpleGUI doesn't support high res displays.

I could have phrased things better here. In this case I was referring to scaling higher than 100% to compensate for high resolutions on small displays. To fix this one I had to roll my own [scaling detection and add multipliers](https://github.com/unexpectedpanda/retool/blob/f0024d17f19b16ad73a53ea9c6a3545db08a8472/retool-gui.py#L40) to UI element widths based on that so the layout didn't get messed up.

> I'm not sure if your project uses PySimpleGUIQt anymore though. I don't see anything in the repo other than in the Wiki and this issue.

[It does](https://github.com/unexpectedpanda/retool/blob/f0024d17f19b16ad73a53ea9c6a3545db08a8472/retool-gui.py#L11)! I'm in the middle of a rewrite at the moment for the CLI portion, but when I get to the GUI bit I'm happy to try out the alpha.
