### ISSUE TITLE
Wrong region/version of Ducktales 2 selected from NES set

### ISSUE THREAD

**Issue by iGom** [unexpectedpanda/retool#97]
**Describe the bug**
The retool always seems to choose the French version of Ducktales 2 and ignore selected regions, in my case World and USA (with the option to prefer roms from modern platforms) over France.

from auto keep-remove list
```
+ DuckTales (World) (The Disney Afternoon Collection) (Unl)
	- DuckTales (Europe)
	- DuckTales (USA)
	- Wanpaku Duck Yume Bouken (Japan)
+ DuckTales 2 (France)
	- DuckTales 2 (Europe)
	- DuckTales 2 (Germany)
	- DuckTales 2 (Japan)
	- DuckTales 2 (USA)
	- DuckTales 2 (World) (The Disney Afternoon Collection) (Unl)
```

**Expected behavior**
select correct rom

**Operating system**
- [ ] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [x] Other (Linux 5.13.0-1-MANJARO x86_64)

**Retool edition**
- [ ] retool-gui.exe
- [ ] retool.py
- [x] retool-gui.py

**Retool version**
GUI 0.10
CLI 0.94

**GUI settings only, not used by the CLI.**
```
gui settings:
- z
- log
- exclude: aBcdDoP
```

[user-config.txt](https://github.com/unexpectedpanda/retool/files/6721838/user-config.txt)

**Comment by iGom** [comment]
[user-config.txt](https://github.com/unexpectedpanda/retool/files/6721836/user-config.txt)

**Comment by unexpectedpanda** [comment]
Surreal &mdash; yep, this is a problem. It seems at first glance to be triggered by the selection of modern editions (I'm guessing the `Unl` in there doesn't help either). Even then, it shouldn't be selecting France looking at your region order. I'll do some digging and see what I can find.

**Comment by unexpectedpanda** [comment]
While modern and unlicensed titles play a part in the issue, the base problem is more fundamental. When selecting a cross-region parent I'm modifying a list that I'm simultaneously iterating through in a `for` loop &mdash; never a great idea. This will be fixed in 0.95. It might be a day or two.

You still won't get the _DuckTales_ modern versions as the parents in the fixed version though, as `(Unl)` titles are meant to be demoted cross-region by default. To get around this, I'll create a new option, _Don't demote unlicensed (Unl) titles_ that you'll have to select.

**Comment by iGom** [comment]
I see, thanks
By the way the Ducktales is not the only game affected by this, the Darkwing Duck is affected too. 
I can't write now if other games are also affected, as I'm not at the PC.

**Comment by unexpectedpanda** [comment]
0.95 should fix your woes &mdash; give it a try!

**Comment by iGom** [comment]
Yep, it works now! Thanks!
